"""hec/dual_search.py — why the DUAL (separating-inequality) route to proving
s=111 non-tree-realizable is structurally BLOCKED, demonstrated empirically, and
a grounded reframe of where the tree-region boundary actually is.

This module deliberately does NOT implement a sample-separation search. That
approach is geometrically vacuous, and this file exists to PROVE that (so the
vacuity is recorded, not merely suspected) and to redirect at the real question.

THE DUAL IDEA (and why it is appealing). Farkas/LP duality: a point is either in
a convex cone, or there is a separating hyperplane. So one might hope to PROVE
s=111 non-tree-realizable by finding a coefficient vector c with c·v <= 0 for
every tree-realizable v but c·v_111 > 0 — a certificate of absence the primal
(find-a-tree) search structurally cannot produce.

WHY IT IS VACUOUS HERE (exact, geometric — not a numerical artifact). s=111 is an
EXTREME RAY of the holographic entropy cone (arXiv:2412.15364: it is one of the
208 SSA-compatible 6-party extreme-ray orbits). BY DEFINITION an extreme ray is
not a non-negative combination of OTHER cone elements. Every tree-realizable
vector lies in the holographic cone. Therefore s=111 is NOT in the convex cone
generated by any finite sample of OTHER (tree-realizable) vectors — so a
separating c ALWAYS exists, for s=111 and for EVERY other extreme ray alike,
including ones that ARE tree-realizable. The separation says nothing about
tree-realizability; it only re-expresses extremality.

THE EMPIRICAL REDUCTIO (demonstrate_vacuity). Run the naive separation on vectors
KNOWN to be tree-realizable and watch it "certify" them all as non-realizable:
  - n=5: all 19 published C5 extreme rays are tree-realizable (arXiv:2204.00075);
    the LP separates 19/19 from the rest — INCLUDING the rays 10 and 17 controls.
  - n=6: all 148 tree-realizable orbits (arXiv:2412.15364) — the LP separates
    148/148 from the other 147.
  - s=111 and s=207 are separated at the identical 100% rate.
A method that "proves" 148/148 + 19/19 KNOWN-realizable rays non-realizable
proves nothing about s=111. (GATE A of the proposed tool — "must FAIL to separate
a known-realizable vector" — fails for EVERY extreme ray, by extremality. It is
not a code bug to fix; it is the method being wrong for this geometry.)

THE REFRAME — where the tree-region boundary actually is (tree_boundary_summary).
The holographic cone is polyhedral; its FACETS are entropy inequalities (SA, SSA,
MMI, and higher-n facets — known for n<=5, partial for n=6 per arXiv:2309.06296).
s=111 satisfies all of them (it is holographic). The TREE-realizable region is a
subset of the holographic cone, but it is NOT known to be carved out by any
finite set of linear facets distinct from the holographic ones. Its boundary is
characterized COMBINATORIALLY, not polyhedrally:
  - simple trees: chordality iff (arXiv:2512.24490) — simple-forest-realizable iff
    the correlation-hypergraph line graph is chordal; a condition on the PMI
    (vanishing-mutual-information) pattern, not a linear inequality;
  - non-simple trees: fine-graining (arXiv:2512.18702, 2412.18018) — tree-
    realizable iff SOME party-splitting refinement is chordal and coarse-grains
    back; a search over an UNBOUNDED refinement space.
So a dual/facet certificate of non-tree-realizability would need a tree-region
facet NOT implied by the holographic facets — none is known, and if trees realize
the full holographic cone (the tree conjecture, arXiv:2204.00075) none EXISTS. The
honest route to rigidity is the combinatorial one: prove NO chordal fine-graining
exists — a structural/inductive argument over the refinement space (the "deep
derivation"), which neither a point-sample nor an LP can supply. The contraction-
map method (arXiv:2204.00075) proves an inequality VALID on the cone (the facet /
primal side); it is not a separation oracle for tree-vs-graph.

HARD RULES honored: no "rigid"/"non-realizable"/"proven" claim about s=111 is made
anywhere — the entire point is that the dual method CANNOT make one. Floats only
illustrate the separation happening; the vacuity itself is an exact geometric
fact (extremality). Suspects {110,145,168} are not touched.

Reproduce: .venv/bin/python -m hec.dual_search
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
from scipy.optimize import linprog

from hec.c5_data import C5_EXTREME_RAYS
from hec.obstruction_search import load_n6_rays, tree_realizable_indices

REPORTS = pathlib.Path(__file__).resolve().parent.parent / "reports"


def _separable(target, sample) -> bool:
    """Does a hyperplane separate `target` from the conic hull of `sample`?
    True iff exists c with c·v <= 0 for all v in sample and c·target >= 1,
    c in [-1,1]^m. (Float LP — sufficient to WITNESS that separation succeeds;
    the reason it always succeeds for an extreme ray is exact, see module doc.)"""
    target = np.asarray(target, float)
    m = len(target)
    A = [list(np.asarray(v, float)) for v in sample] + [list(-target)]
    b = [0.0] * len(sample) + [-1.0]
    res = linprog(np.zeros(m), A_ub=np.array(A), b_ub=np.array(b),
                  bounds=[(-1, 1)] * m, method="highs")
    return bool(res.success)


def demonstrate_vacuity(log=print) -> dict:
    """Empirical reductio: the naive separation 'certifies' KNOWN tree-realizable
    extreme rays as non-realizable, at the same 100% rate as s=111/207. A method
    that does this proves nothing. Returns the rates."""
    # n=5: all 19 C5 extreme rays are tree-realizable (arXiv:2204.00075)
    c5 = [np.array(v, float) for v in C5_EXTREME_RAYS]
    n5_hits = [k + 1 for k in range(19)
               if _separable(c5[k], c5[:k] + c5[k + 1:])]
    controls = {k: _separable(c5[k - 1], c5[:k - 1] + c5[k:]) for k in (10, 17)}
    log(f"n=5: separated {len(n5_hits)}/19 KNOWN-tree-realizable C5 rays "
        f"(controls 10,17 separated: {controls[10]},{controls[17]})")

    # n=6: all 148 tree-realizable orbits (arXiv:2412.15364)
    rows = load_n6_rays()
    tv = [np.array(rows[s - 1], float) for s in tree_realizable_indices()]
    n6_hits = sum(_separable(tv[j], tv[:j] + tv[j + 1:]) for j in range(len(tv)))
    log(f"n=6: separated {n6_hits}/148 KNOWN-tree-realizable orbits from the rest")

    orbits = json.loads((pathlib.Path(__file__).resolve().parent.parent / "data" /
                         "targets" / "bulk_cycle_orbits.json").read_text())["orbits"]
    t111 = _separable(orbits["111"], tv)
    t207 = _separable(orbits["207"], tv)
    log(f"targets: s=111 separated={t111}, s=207 separated={t207} "
        f"(same rate as the KNOWN-realizable rays)")

    return {
        "n5_known_realizable_separated": f"{len(n5_hits)}/19",
        "n5_controls_10_17_separated": controls,
        "n6_known_realizable_separated": f"{n6_hits}/148",
        "targets_separated": {"111": t111, "207": t207},
        "false_certificate_rate": "100% — every KNOWN tree-realizable extreme ray "
                                  "is 'separated', so separation is vacuous",
        "why": "s=111 is an EXTREME RAY of the holographic cone; an extreme ray is "
               "never a non-negative combination of other cone elements, so it is "
               "separable from any finite sample of other (tree-realizable) "
               "vectors — exactly as every other extreme ray is. The proposed "
               "GATE A (must fail to separate a known-realizable vector) therefore "
               "fails for EVERY extreme ray: not a code bug, a geometry mismatch.",
    }


def tree_boundary_summary() -> dict:
    """What is actually KNOWN about the facets / defining inequalities of the
    tree-realizable region (grounded in the repo's references). The short answer:
    the boundary is COMBINATORIAL, not a known set of linear facets — which is
    why the dual/facet route has nothing to test s=111 against."""
    return {
        "holographic_cone": "closed convex polyhedral rational cone; facets are "
            "entropy inequalities (SA, SSA, MMI, and higher-n facets). KNOWN "
            "exactly for n<=5; PARTIAL for n=6 (completeness open — arXiv:2309.06296 "
            "ancillary data). s=111/207 satisfy ALL of them (they are holographic — "
            "among the 156 non-violating 6-party orbits of arXiv:2412.15364).",
        "tree_region_facets": "NO finite set of linear facets distinct from the "
            "holographic ones is known to carve out the tree-realizable region. A "
            "dual certificate of non-tree-realizability would have to be a tree-"
            "region facet NOT implied by the holographic facets; none is known, and "
            "if trees realize the full holographic cone (tree conjecture, "
            "arXiv:2204.00075) NONE EXISTS.",
        "simple_tree_boundary": "COMBINATORIAL, not polyhedral: chordality iff "
            "(arXiv:2512.24490) — a vector is simple-forest-realizable iff the line "
            "graph of its correlation hypergraph is chordal; a condition on the "
            "PMI (vanishing-MI) pattern, not a linear inequality. s=111 is "
            "non-chordal, so NOT simple-tree-realizable (this IS settled) — but "
            "that does not decide non-simple trees.",
        "non_simple_tree_boundary": "fine-graining (arXiv:2512.18702, 2412.18018): "
            "tree-realizable iff SOME party-splitting refinement is chordal and "
            "coarse-grains back. The refinement space is UNBOUNDED; the boundary is "
            "the existence of a chordal refinement — combinatorial, not a facet.",
        "contraction_maps": "the contraction-map method (arXiv:2204.00075) proves "
            "an inequality VALID on the cone (the facet/primal side) — it is a "
            "validity prover, NOT a separation oracle for tree-vs-graph; it cannot "
            "certify a vector is OUTSIDE the tree region.",
        "honest_route_to_rigidity": "prove NO chordal fine-graining of s=111 exists "
            "— a structural/inductive argument over the unbounded refinement space "
            "(the 'deep derivation'). Neither a point-sample nor an LP separation "
            "can supply this. The primal search can only ever EXHIBIT a tree, never "
            "refute one (this repo's 2-/3-split runs are bounded negatives, not "
            "proofs). So rigidity, if true, needs the combinatorial characterization "
            "pushed to an impossibility theorem.",
    }


def run(log=print) -> dict:
    log("Demonstrating that the dual sample-separation route is VACUOUS ...")
    vac = demonstrate_vacuity(log)
    out = {
        "what": "Why the dual (separating-inequality) route to proving s=111 "
                "non-tree-realizable is structurally blocked, demonstrated, plus a "
                "grounded reframe of the tree-region boundary.",
        "verdict": "The naive sample-separation method is VACUOUS for this question "
                   "(it separates 100% of KNOWN tree-realizable extreme rays, "
                   "including rays 10/17 and 148/148 n=6 orbits). NO rigidity claim "
                   "about s=111 is or can be made by this route.",
        "vacuity_demonstration": vac,
        "tree_boundary_reframe": tree_boundary_summary(),
        "claim_discipline": "No 'rigid'/'non-realizable'/'proven' statement about "
                            "s=111 appears here; the finding is that the dual route "
                            "CANNOT produce one. s=111/207 remain holographic and "
                            "their tree question OPEN.",
    }
    return out


def write_report(out, out_dir=REPORTS):
    out_dir.mkdir(parents=True, exist_ok=True)
    p = out_dir / "dual_search.json"
    p.write_text(json.dumps(out, indent=2, default=str))
    return p


if __name__ == "__main__":
    R = run()
    print(json.dumps(R["vacuity_demonstration"], indent=2, default=str))
    print("\nreport ->", write_report(R))
